/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.labclase1;

import javax.swing.JOptionPane;

/**
 *
 * @author MINEDUCYT
 */
public class Ejemplo extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo
     */
    public Ejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbTituloVentana = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbCorrreo = new javax.swing.JLabel();
        lbCarreras = new javax.swing.JLabel();
        lbCiclos = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        cbCarreras = new javax.swing.JComboBox<>();
        rbCiclo01 = new javax.swing.JRadioButton();
        rbCiclo02 = new javax.swing.JRadioButton();
        btRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVentana.setText("DATOS DEL ALUMNO");

        lbNombres.setText("Nombres:");

        lbApellidos.setText("Apellidos:");

        lbCorrreo.setText("Correo:");

        lbCarreras.setText("Carrera:");

        lbCiclos.setText("Ciclo Actual");

        cbCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Ing. Sistemas", "Ing. Electrica", "Ing. Industrial", "Ing. Agronegocios" }));

        buttonGroup1.add(rbCiclo01);
        rbCiclo01.setText("Ciclo 01");

        buttonGroup1.add(rbCiclo02);
        rbCiclo02.setText("Ciclo 02");

        btRegistrar.setText("REGISTRAR");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCiclos)
                    .addComponent(lbCorrreo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCarreras, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombres, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfNombres)
                        .addComponent(tfApellidos)
                        .addComponent(tfCorreo)
                        .addComponent(cbCarreras, 0, 265, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btRegistrar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbCiclo01)
                            .addGap(39, 39, 39)
                            .addComponent(rbCiclo02))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTituloVentana)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloVentana)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombres)
                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellidos)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorrreo)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarreras)
                    .addComponent(cbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCiclos)
                    .addComponent(rbCiclo01)
                    .addComponent(rbCiclo02))
                .addGap(33, 33, 33)
                .addComponent(btRegistrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        // TODO add your handling code here:
        String cicloActual = "";
        String carrera = "";
        String nombres = "";
        String apellidos = "";
        String correo = "";
        String carreraSeleccionada = (String)this.cbCarreras.getSelectedItem();
        
        //Validacion de caja de texto de Nombres
        if(this.tfNombres.getText().isEmpty()){
            nombres = "-1";
            JOptionPane.showMessageDialog(this, "Caja de nombres vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            nombres = "1";
        }
        
        //Validacion de caja de texto de Apellidos
        if(this.tfApellidos.getText().isEmpty()){
            apellidos = "-1";
            JOptionPane.showMessageDialog(this, "Caja de apellidos vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            apellidos = "1";
        }
        
        //Validacion de caja de texto de Correo
        if(this.tfCorreo.getText().isEmpty()){
            correo = "-1";
            JOptionPane.showMessageDialog(this, "Caja de correo vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            correo = "1";
        }
        
        //Validacion opcion por defecto
        if("Seleccione una opción".equals(carreraSeleccionada)){
            carrera = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione una carrera. ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //Validacion de ciclo
        if(this.rbCiclo01.isSelected()){
            cicloActual = "01";
        }else if(this.rbCiclo02.isSelected()){
            cicloActual = "02";
        }else{
            cicloActual = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione un ciclo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(!"-1".equals(cicloActual) && !"-1".equals(carrera) && !"-1".equals(nombres) && !"-1".equals(apellidos) && !"-1".equals(correo)){
            JOptionPane.showMessageDialog(this, "Registro exitoso de " 
                + this.tfNombres.getText() + " "
                + this.tfApellidos.getText()
                + " estudiante de la carrera de "
                + this.cbCarreras.getSelectedItem()
                + " con el correo "
                + this.tfCorreo.getText()
                + " en el ciclo "
                + cicloActual  
            );
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCarreras;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCarreras;
    private javax.swing.JLabel lbCiclos;
    private javax.swing.JLabel lbCorrreo;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbTituloVentana;
    private javax.swing.JRadioButton rbCiclo01;
    private javax.swing.JRadioButton rbCiclo02;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNombres;
    // End of variables declaration//GEN-END:variables
}
